alias l=ls
alias ll='ls -l'
alias la='ls -lA'
alias py=python3
alias latest='ls -t | head'
alias dvorak="xkbcomp $HOME/.xkb.xkm $DISPLAY"
alias jisho=tagainijisho
alias untar='tar -xf'
alias horiz='synclient HorizTwoFingerScroll=1'
alias wine_jp='LANG=ja_JP.UTF-8 wine'
alias hide='gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca &>/dev/null'
alias show='gnome-shell-extension-tool -d hidetopbar@mathieu.bidon.ca &>/dev/null'
alias 1920='xrandr -s 1920x1200'
alias 1024='xrandr -s 1024x768'
alias 800='xrandr -s 800x600'
alias dvorak-txt='loadkeys dvorak'
alias core-temp='sensors | grep Core'
alias ys="yum search"                       
alias yp="yum info"                         
alias yl="yum list"                         
alias yu="sudo yum update"                  
alias yi="sudo yum install"                 
alias yr="sudo yum remove"                  
alias gi="git commit"
alias gu="git pull"
alias gp="git push"
alias ga="git add"
alias gb="git branch"alias sizes="du -sh"
alias sizes="du -sh *"
alias findhere="find -maxdepth 1"
alias ldc=ldc2
alias sbcl=/home/tucker/usr/bin/sbcl
alias emacs-compile='emacs -batch -Q -f batch-byte-compile'
alias qemu='/home/tucker/usr/bin/qemu-system-x86_64'
alias sbcl-term='sbcl --userinit /home/tucker/.sbcl-term'
alias em="emacs -Q -nw"
alias cd..="cd .."
alias emacsc=emacsclient
alias emacscx='emacsclient -c'
