(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)
(package-initialize ())
(add-to-list 'load-path "/home/tucker/.emacs.d/my-elisp")
;;(add-to-list 'load-path "/home/tucker/Repo/emacs/slime/")
;;(add-to-list 'load-path "/home/tucker/Repo/emacs/slime/contrib/")
(setq inferior-lisp-program "/home/tucker/usr/bin/sbcl")
(load "/home/tucker/Repo/emacs/geiser/elisp/geiser-load")
(load (expand-file-name "~/quicklisp/slime-helper.el"))
(defalias 'yes-or-no-p 'y-or-n-p)
(require 'llvm-mode)
(require 'ats-mode)
(require 'rainbow-delimiters)
(require 'auto-complete)
(require 'quack)
(require 'geiser)
(require 'w3m)
(require 'go-mode)
(require 'shen-mode)
(require 'magit)
(require 'wind-swap)
(global-rainbow-delimiters-mode)
(global-auto-complete-mode)
(windmove-default-keybindings)
