#Bash Aliases
#simple/common alises
alias cd..="cd .."
alias em="emacs -Q -nw"
alias emacs-compile='emacs -batch -Q -f batch-byte-compile'
alias emacsc=emacsclient
alias emacscx='emacsclient -c'
alias emc='emacsclient -c -nw'
alias eshell="emacsclient -a \"\" -nw -e '(eshell)'"
alias findhere="find -maxdepth 1"
alias l=ls
alias la='ls -lA'
alias latest='ls -t | head'
alias ll='ls -l'
alias loadrc=". ~/.bashrc"
alias ls="ls --color=auto"
alias py=python3
alias rsync="rsync -av"
alias sizes="du -sh *"
alias untar='tar -xf'
#X aliases
alias 1024='xrandr -s 1024x768'
alias 1920='xrandr -s 1920x1200'
alias 800='xrandr -s 800x600'
alias horiz='synclient HorizTwoFingerScroll=1'
alias startXephyr="Xephyr :10 -ac -br -noreset -screen 1152x720"
alias xclip="xclip -selection clipboard"
#yum shortcuts
# alias yi="sudo yum install"
# alias yl="yum list"
# alias yp="yum info"
# alias yr="sudo yum remove"
# alias ys="yum search"
# alias yu="sudo yum update"
#git shortcuts
alias ga="git add"
alias gb="git branch"
alias gi="git commit"
alias gp="git push"
alias gu="git pull"
#pacman/yaourt shortcuts
alias paci=pacin
alias pacin='sudo pacman -S'
alias pacinl='sudo pacman -U'
alias pacq='pacman -Q'
alias pacrm='sudo pacman -R'
alias pacs='pacman -Ss'
alias pacupg='sudo pacman -Syu'
alias yb='yaourt -Sba'
alias yi='yaourt -Sa'
alias yil='yaourt -Sda'
alias yp='yaourt -Sai'
alias yq='yaourt -Q'
alias yrm='yaourt -R'
alias ys='yaourt -Sas'
alias yu='yaourt -Sayu'
#transmission shortcuts
alias tr-cli='transmission-cli'
alias tr-daemon='transmission-daemon'
alias tr-gui='transmission-gtk'
alias tr-remote='transmission-remote'
#System commands/status aliases
alias clear-ram="sudo bash -c 'sync;echo 3 >/proc/sys/vm/drop_caches'"
alias core-temp='sensors | grep Core'
#less common program shortcuts/aliases
alias emelfm2='GTK2_RC_FILES="/home/tucker/.gtkrc-zenburn" emelfm2'
alias jisho=tagainijisho
alias ldc=ldc2
alias links=elinks
alias sbcl-term='sbcl --userinit /home/tucker/.sbcl-term'
alias sbcl=/home/tucker/usr/bin/sbcl
alias wine_jp='LANG=ja_JP.UTF-8 wine'
#Computer Specific Aliases
